name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
       - mlflow==2.18.0
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - xgboost==2.1.4
name: mlflow-env
