name: Train and Log Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Verify environment setup
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Run MLflow Project
      shell: bash -l {0}
      working-directory: ./MLProject
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: mlflow run .

    - name: Upload trained model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/artifacts/xgboost_best_model.pkl
