name: Train and Log Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: graduate_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false
      
    - name: Verify environment
      run: |
        conda info
        conda list

    - name: Install dependencies
      run: pip install mlflow xgboost scikit-learn pandas joblib

    - name: Set MLflow credentials
      run: |
        echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . -P train_path=dataset_preprocessing/train_clean.csv -P test_path=dataset_preprocessing/test_clean.csv

    - name: Upload trained model to GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/artifacts/xgboost_best_model.pkl
